# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: test.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ntest.proto\x12\x04test\"$\n\tMyRequest\x12\x17\n\x0fmessage_content\x18\x01 \x01(\t\"%\n\nMyResponse\x12\x17\n\x0fserialized_data\x18\x01 \x03(\t2:\n\tMyService\x12-\n\x08MyMethod\x12\x0f.test.MyRequest\x1a\x10.test.MyResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'test_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MYREQUEST']._serialized_start=20
  _globals['_MYREQUEST']._serialized_end=56
  _globals['_MYRESPONSE']._serialized_start=58
  _globals['_MYRESPONSE']._serialized_end=95
  _globals['_MYSERVICE']._serialized_start=97
  _globals['_MYSERVICE']._serialized_end=155
# @@protoc_insertion_point(module_scope)
